// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Chat.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit<::Chat::UserAlreadyExists> iceC_Chat_UserAlreadyExists_init("::Chat::UserAlreadyExists");

const ::std::string iceC_Chat_User_ids[2] =
{
    "::Chat::User",
    "::Ice::Object"
};
const ::std::string iceC_Chat_User_ops[] =
{
    "SendMessage",
    "SendPrivateMessage",
    "getName",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Chat_User_SendMessage_name = "SendMessage";
const ::std::string iceC_Chat_User_SendPrivateMessage_name = "SendPrivateMessage";
const ::std::string iceC_Chat_User_getName_name = "getName";

const ::std::string iceC_Chat_Server_ids[2] =
{
    "::Chat::Server",
    "::Ice::Object"
};
const ::std::string iceC_Chat_Server_ops[] =
{
    "ChangePassword",
    "CreateRoom",
    "FindRoom",
    "RegisterRoomFactory",
    "RegisterUser",
    "UnregisterRoomFactory",
    "getPassword",
    "getRooms",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Chat_Server_CreateRoom_name = "CreateRoom";
const ::std::string iceC_Chat_Server_getRooms_name = "getRooms";
const ::std::string iceC_Chat_Server_FindRoom_name = "FindRoom";
const ::std::string iceC_Chat_Server_RegisterUser_name = "RegisterUser";
const ::std::string iceC_Chat_Server_ChangePassword_name = "ChangePassword";
const ::std::string iceC_Chat_Server_getPassword_name = "getPassword";
const ::std::string iceC_Chat_Server_RegisterRoomFactory_name = "RegisterRoomFactory";
const ::std::string iceC_Chat_Server_UnregisterRoomFactory_name = "UnregisterRoomFactory";

const ::std::string iceC_Chat_Room_ids[2] =
{
    "::Chat::Room",
    "::Ice::Object"
};
const ::std::string iceC_Chat_Room_ops[] =
{
    "AddUser",
    "Destroy",
    "LeaveRoom",
    "SendMessage",
    "getName",
    "getUsers",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Chat_Room_getName_name = "getName";
const ::std::string iceC_Chat_Room_getUsers_name = "getUsers";
const ::std::string iceC_Chat_Room_AddUser_name = "AddUser";
const ::std::string iceC_Chat_Room_SendMessage_name = "SendMessage";
const ::std::string iceC_Chat_Room_Destroy_name = "Destroy";
const ::std::string iceC_Chat_Room_LeaveRoom_name = "LeaveRoom";

const ::std::string iceC_Chat_RoomFactory_ids[2] =
{
    "::Chat::RoomFactory",
    "::Ice::Object"
};
const ::std::string iceC_Chat_RoomFactory_ops[] =
{
    "createRoom",
    "getRooms",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};
const ::std::string iceC_Chat_RoomFactory_createRoom_name = "createRoom";
const ::std::string iceC_Chat_RoomFactory_getRooms_name = "getRooms";

}

Chat::UserAlreadyExists::~UserAlreadyExists()
{
}

const ::std::string&
Chat::UserAlreadyExists::ice_staticId()
{
    static const ::std::string typeId = "::Chat::UserAlreadyExists";
    return typeId;
}

bool
Chat::User::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Chat_User_ids, iceC_Chat_User_ids + 2, s);
}

::std::vector<::std::string>
Chat::User::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Chat_User_ids[0], &iceC_Chat_User_ids[2]);
}

::std::string
Chat::User::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Chat::User::ice_staticId()
{
    static const ::std::string typeId = "::Chat::User";
    return typeId;
}

bool
Chat::User::_iceD_SendMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<::Chat::RoomPrx> iceP_where;
    ::std::shared_ptr<::Chat::UserPrx> iceP_who;
    ::std::string iceP_message;
    istr->readAll(iceP_where, iceP_who, iceP_message);
    inS.endReadParams();
    this->SendMessage(::std::move(iceP_where), ::std::move(iceP_who), ::std::move(iceP_message), current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::User::_iceD_SendPrivateMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<::Chat::UserPrx> iceP_who;
    ::std::string iceP_message;
    istr->readAll(iceP_who, iceP_message);
    inS.endReadParams();
    this->SendPrivateMessage(::std::move(iceP_who), ::std::move(iceP_message), current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::User::_iceD_getName(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    ::std::string ret = this->getName(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::User::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Chat_User_ops, iceC_Chat_User_ops + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Chat_User_ops)
    {
        case 0:
        {
            return _iceD_SendMessage(in, current);
        }
        case 1:
        {
            return _iceD_SendPrivateMessage(in, current);
        }
        case 2:
        {
            return _iceD_getName(in, current);
        }
        case 3:
        {
            return _iceD_ice_id(in, current);
        }
        case 4:
        {
            return _iceD_ice_ids(in, current);
        }
        case 5:
        {
            return _iceD_ice_isA(in, current);
        }
        case 6:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

bool
Chat::Server::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Chat_Server_ids, iceC_Chat_Server_ids + 2, s);
}

::std::vector<::std::string>
Chat::Server::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Chat_Server_ids[0], &iceC_Chat_Server_ids[2]);
}

::std::string
Chat::Server::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Chat::Server::ice_staticId()
{
    static const ::std::string typeId = "::Chat::Server";
    return typeId;
}

bool
Chat::Server::_iceD_CreateRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    ::std::shared_ptr<::Chat::RoomPrx> ret = this->CreateRoom(::std::move(iceP_name), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::Server::_iceD_getRooms(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    ::Chat::RoomList ret = this->getRooms(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::Server::_iceD_FindRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    ::std::shared_ptr<::Chat::RoomPrx> ret = this->FindRoom(::std::move(iceP_name), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::Server::_iceD_RegisterUser(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    ::std::string iceP_password;
    istr->readAll(iceP_name, iceP_password);
    inS.endReadParams();
    this->RegisterUser(::std::move(iceP_name), ::std::move(iceP_password), current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Server::_iceD_ChangePassword(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<::Chat::UserPrx> iceP_user;
    ::std::string iceP_oldpassword;
    ::std::string iceP_newpassword;
    istr->readAll(iceP_user, iceP_oldpassword, iceP_newpassword);
    inS.endReadParams();
    this->ChangePassword(::std::move(iceP_user), ::std::move(iceP_oldpassword), ::std::move(iceP_newpassword), current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Server::_iceD_getPassword(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_user;
    istr->readAll(iceP_user);
    inS.endReadParams();
    this->getPassword(::std::move(iceP_user), current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Server::_iceD_RegisterRoomFactory(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<::Chat::RoomFactoryPrx> iceP_factory;
    istr->readAll(iceP_factory);
    inS.endReadParams();
    this->RegisterRoomFactory(::std::move(iceP_factory), current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Server::_iceD_UnregisterRoomFactory(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<::Chat::RoomFactoryPrx> iceP_factory;
    istr->readAll(iceP_factory);
    inS.endReadParams();
    this->UnregisterRoomFactory(::std::move(iceP_factory), current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Server::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Chat_Server_ops, iceC_Chat_Server_ops + 12, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Chat_Server_ops)
    {
        case 0:
        {
            return _iceD_ChangePassword(in, current);
        }
        case 1:
        {
            return _iceD_CreateRoom(in, current);
        }
        case 2:
        {
            return _iceD_FindRoom(in, current);
        }
        case 3:
        {
            return _iceD_RegisterRoomFactory(in, current);
        }
        case 4:
        {
            return _iceD_RegisterUser(in, current);
        }
        case 5:
        {
            return _iceD_UnregisterRoomFactory(in, current);
        }
        case 6:
        {
            return _iceD_getPassword(in, current);
        }
        case 7:
        {
            return _iceD_getRooms(in, current);
        }
        case 8:
        {
            return _iceD_ice_id(in, current);
        }
        case 9:
        {
            return _iceD_ice_ids(in, current);
        }
        case 10:
        {
            return _iceD_ice_isA(in, current);
        }
        case 11:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

bool
Chat::Room::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Chat_Room_ids, iceC_Chat_Room_ids + 2, s);
}

::std::vector<::std::string>
Chat::Room::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Chat_Room_ids[0], &iceC_Chat_Room_ids[2]);
}

::std::string
Chat::Room::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Chat::Room::ice_staticId()
{
    static const ::std::string typeId = "::Chat::Room";
    return typeId;
}

bool
Chat::Room::_iceD_getName(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    ::std::string ret = this->getName(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::Room::_iceD_getUsers(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    ::Chat::UserList ret = this->getUsers(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::Room::_iceD_AddUser(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<::Chat::UserPrx> iceP_who;
    ::std::string iceP_password;
    istr->readAll(iceP_who, iceP_password);
    inS.endReadParams();
    this->AddUser(::std::move(iceP_who), ::std::move(iceP_password), current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Room::_iceD_SendMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<::Chat::UserPrx> iceP_who;
    ::std::string iceP_message;
    ::std::string iceP_passwd;
    istr->readAll(iceP_who, iceP_message, iceP_passwd);
    inS.endReadParams();
    this->SendMessage(::std::move(iceP_who), ::std::move(iceP_message), ::std::move(iceP_passwd), current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Room::_iceD_Destroy(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    this->Destroy(current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Room::_iceD_LeaveRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::shared_ptr<::Chat::UserPrx> iceP_who;
    ::std::string iceP_passwd;
    istr->readAll(iceP_who, iceP_passwd);
    inS.endReadParams();
    this->LeaveRoom(::std::move(iceP_who), ::std::move(iceP_passwd), current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Room::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Chat_Room_ops, iceC_Chat_Room_ops + 10, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Chat_Room_ops)
    {
        case 0:
        {
            return _iceD_AddUser(in, current);
        }
        case 1:
        {
            return _iceD_Destroy(in, current);
        }
        case 2:
        {
            return _iceD_LeaveRoom(in, current);
        }
        case 3:
        {
            return _iceD_SendMessage(in, current);
        }
        case 4:
        {
            return _iceD_getName(in, current);
        }
        case 5:
        {
            return _iceD_getUsers(in, current);
        }
        case 6:
        {
            return _iceD_ice_id(in, current);
        }
        case 7:
        {
            return _iceD_ice_ids(in, current);
        }
        case 8:
        {
            return _iceD_ice_isA(in, current);
        }
        case 9:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

bool
Chat::RoomFactory::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Chat_RoomFactory_ids, iceC_Chat_RoomFactory_ids + 2, s);
}

::std::vector<::std::string>
Chat::RoomFactory::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_Chat_RoomFactory_ids[0], &iceC_Chat_RoomFactory_ids[2]);
}

::std::string
Chat::RoomFactory::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Chat::RoomFactory::ice_staticId()
{
    static const ::std::string typeId = "::Chat::RoomFactory";
    return typeId;
}

bool
Chat::RoomFactory::_iceD_createRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->readAll(iceP_name);
    inS.endReadParams();
    ::std::shared_ptr<::Chat::RoomPrx> ret = this->createRoom(::std::move(iceP_name), current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::RoomFactory::_iceD_getRooms(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Normal, current.mode);
    inS.readEmptyParams();
    ::Chat::RoomList ret = this->getRooms(current);
    auto ostr = inS.startWriteParams();
    ostr->writeAll(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::RoomFactory::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Chat_RoomFactory_ops, iceC_Chat_RoomFactory_ops + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Chat_RoomFactory_ops)
    {
        case 0:
        {
            return _iceD_createRoom(in, current);
        }
        case 1:
        {
            return _iceD_getRooms(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
Chat::UserPrx::_iceI_SendMessage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<::Chat::RoomPrx>& iceP_where, const ::std::shared_ptr<::Chat::UserPrx>& iceP_who, const ::std::string& iceP_message, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Chat_User_SendMessage_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_where, iceP_who, iceP_message);
        },
        nullptr);
}

void
Chat::UserPrx::_iceI_SendPrivateMessage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<::Chat::UserPrx>& iceP_who, const ::std::string& iceP_message, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Chat_User_SendPrivateMessage_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_who, iceP_message);
        },
        nullptr);
}

void
Chat::UserPrx::_iceI_getName(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Chat_User_getName_name);
    outAsync->invoke(iceC_Chat_User_getName_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
Chat::UserPrx::_newInstance() const
{
    return ::IceInternal::createProxy<UserPrx>();
}

const ::std::string&
Chat::UserPrx::ice_staticId()
{
    return Chat::User::ice_staticId();
}

void
Chat::ServerPrx::_iceI_CreateRoom(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::shared_ptr<::Chat::RoomPrx>>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Chat_Server_CreateRoom_name);
    outAsync->invoke(iceC_Chat_Server_CreateRoom_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}

void
Chat::ServerPrx::_iceI_getRooms(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::Chat::RoomList>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Chat_Server_getRooms_name);
    outAsync->invoke(iceC_Chat_Server_getRooms_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}

void
Chat::ServerPrx::_iceI_FindRoom(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::shared_ptr<::Chat::RoomPrx>>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Chat_Server_FindRoom_name);
    outAsync->invoke(iceC_Chat_Server_FindRoom_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}

void
Chat::ServerPrx::_iceI_RegisterUser(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_name, const ::std::string& iceP_password, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Chat_Server_RegisterUser_name);
    outAsync->invoke(iceC_Chat_Server_RegisterUser_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name, iceP_password);
        },
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const ::Chat::UserAlreadyExists&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}

void
Chat::ServerPrx::_iceI_ChangePassword(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<::Chat::UserPrx>& iceP_user, const ::std::string& iceP_oldpassword, const ::std::string& iceP_newpassword, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Chat_Server_ChangePassword_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_user, iceP_oldpassword, iceP_newpassword);
        },
        nullptr);
}

void
Chat::ServerPrx::_iceI_getPassword(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::string& iceP_user, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Chat_Server_getPassword_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_user);
        },
        nullptr);
}

void
Chat::ServerPrx::_iceI_RegisterRoomFactory(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<::Chat::RoomFactoryPrx>& iceP_factory, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Chat_Server_RegisterRoomFactory_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_factory);
        },
        nullptr);
}

void
Chat::ServerPrx::_iceI_UnregisterRoomFactory(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<::Chat::RoomFactoryPrx>& iceP_factory, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Chat_Server_UnregisterRoomFactory_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_factory);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
Chat::ServerPrx::_newInstance() const
{
    return ::IceInternal::createProxy<ServerPrx>();
}

const ::std::string&
Chat::ServerPrx::ice_staticId()
{
    return Chat::Server::ice_staticId();
}

void
Chat::RoomPrx::_iceI_getName(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::string>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Chat_Room_getName_name);
    outAsync->invoke(iceC_Chat_Room_getName_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}

void
Chat::RoomPrx::_iceI_getUsers(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::Chat::UserList>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Chat_Room_getUsers_name);
    outAsync->invoke(iceC_Chat_Room_getUsers_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}

void
Chat::RoomPrx::_iceI_AddUser(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<::Chat::UserPrx>& iceP_who, const ::std::string& iceP_password, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Chat_Room_AddUser_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_who, iceP_password);
        },
        nullptr);
}

void
Chat::RoomPrx::_iceI_SendMessage(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<::Chat::UserPrx>& iceP_who, const ::std::string& iceP_message, const ::std::string& iceP_passwd, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Chat_Room_SendMessage_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_who, iceP_message, iceP_passwd);
        },
        nullptr);
}

void
Chat::RoomPrx::_iceI_Destroy(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Chat_Room_Destroy_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}

void
Chat::RoomPrx::_iceI_LeaveRoom(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<void>>& outAsync, const ::std::shared_ptr<::Chat::UserPrx>& iceP_who, const ::std::string& iceP_passwd, const ::Ice::Context& context)
{
    outAsync->invoke(iceC_Chat_Room_LeaveRoom_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_who, iceP_passwd);
        },
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
Chat::RoomPrx::_newInstance() const
{
    return ::IceInternal::createProxy<RoomPrx>();
}

const ::std::string&
Chat::RoomPrx::ice_staticId()
{
    return Chat::Room::ice_staticId();
}

void
Chat::RoomFactoryPrx::_iceI_createRoom(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::std::shared_ptr<::Chat::RoomPrx>>>& outAsync, const ::std::string& iceP_name, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Chat_RoomFactory_createRoom_name);
    outAsync->invoke(iceC_Chat_RoomFactory_createRoom_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_name);
        },
        nullptr);
}

void
Chat::RoomFactoryPrx::_iceI_getRooms(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<::Chat::RoomList>>& outAsync, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_Chat_RoomFactory_getRooms_name);
    outAsync->invoke(iceC_Chat_RoomFactory_getRooms_name, ::Ice::OperationMode::Normal, ::Ice::FormatType::DefaultFormat, context,
        nullptr,
        nullptr);
}

::std::shared_ptr<::Ice::ObjectPrx>
Chat::RoomFactoryPrx::_newInstance() const
{
    return ::IceInternal::createProxy<RoomFactoryPrx>();
}

const ::std::string&
Chat::RoomFactoryPrx::ice_staticId()
{
    return Chat::RoomFactory::ice_staticId();
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_Chat_User_SendMessage_name = "SendMessage";

const ::std::string iceC_Chat_User_SendPrivateMessage_name = "SendPrivateMessage";

const ::std::string iceC_Chat_User_getName_name = "getName";

const ::std::string iceC_Chat_Server_CreateRoom_name = "CreateRoom";

const ::std::string iceC_Chat_Server_getRooms_name = "getRooms";

const ::std::string iceC_Chat_Server_FindRoom_name = "FindRoom";

const ::std::string iceC_Chat_Server_RegisterUser_name = "RegisterUser";

const ::std::string iceC_Chat_Server_ChangePassword_name = "ChangePassword";

const ::std::string iceC_Chat_Server_getPassword_name = "getPassword";

const ::std::string iceC_Chat_Server_RegisterRoomFactory_name = "RegisterRoomFactory";

const ::std::string iceC_Chat_Server_UnregisterRoomFactory_name = "UnregisterRoomFactory";

const ::std::string iceC_Chat_Room_getName_name = "getName";

const ::std::string iceC_Chat_Room_getUsers_name = "getUsers";

const ::std::string iceC_Chat_Room_AddUser_name = "AddUser";

const ::std::string iceC_Chat_Room_SendMessage_name = "SendMessage";

const ::std::string iceC_Chat_Room_Destroy_name = "Destroy";

const ::std::string iceC_Chat_Room_LeaveRoom_name = "LeaveRoom";

const ::std::string iceC_Chat_RoomFactory_createRoom_name = "createRoom";

const ::std::string iceC_Chat_RoomFactory_getRooms_name = "getRooms";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::Chat::UserAlreadyExists> iceC_Chat_UserAlreadyExists_init("::Chat::UserAlreadyExists");

}

Chat::UserAlreadyExists::~UserAlreadyExists() throw()
{
}

::std::string
Chat::UserAlreadyExists::ice_id() const
{
    return "::Chat::UserAlreadyExists";
}

Chat::UserAlreadyExists*
Chat::UserAlreadyExists::ice_clone() const
{
    return new UserAlreadyExists(*this);
}

void
Chat::UserAlreadyExists::ice_throw() const
{
    throw *this;
}

void
Chat::UserAlreadyExists::_writeImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice("::Chat::UserAlreadyExists", -1, true);
    Ice::StreamWriter< ::Chat::UserAlreadyExists, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Chat::UserAlreadyExists::_readImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::Chat::UserAlreadyExists, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
::IceProxy::Ice::Object* ::IceProxy::Chat::upCast(::IceProxy::Chat::User* p) { return p; }

void
::IceProxy::Chat::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::Chat::User>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Chat::User;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::Chat::User::_iceI_begin_SendMessage(const ::Chat::RoomPrx& iceP_where, const ::Chat::UserPrx& iceP_who, const ::std::string& iceP_message, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_User_SendMessage_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_User_SendMessage_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_where);
        ostr->write(iceP_who);
        ostr->write(iceP_message);
        result->endWriteParams();
        result->invoke(iceC_Chat_User_SendMessage_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::User::end_SendMessage(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Chat_User_SendMessage_name);
}

::Ice::AsyncResultPtr
IceProxy::Chat::User::_iceI_begin_SendPrivateMessage(const ::Chat::UserPrx& iceP_who, const ::std::string& iceP_message, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_User_SendPrivateMessage_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_User_SendPrivateMessage_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_who);
        ostr->write(iceP_message);
        result->endWriteParams();
        result->invoke(iceC_Chat_User_SendPrivateMessage_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::User::end_SendPrivateMessage(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Chat_User_SendPrivateMessage_name);
}

::Ice::AsyncResultPtr
IceProxy::Chat::User::_iceI_begin_getName(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Chat_User_getName_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_User_getName_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_User_getName_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_Chat_User_getName_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::std::string
IceProxy::Chat::User::end_getName(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Chat_User_getName_name);
    ::std::string ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::IceProxy::Ice::Object*
IceProxy::Chat::User::_newInstance() const
{
    return new User;
}

const ::std::string&
IceProxy::Chat::User::ice_staticId()
{
    return ::Chat::User::ice_staticId();
}
::IceProxy::Ice::Object* ::IceProxy::Chat::upCast(::IceProxy::Chat::Server* p) { return p; }

void
::IceProxy::Chat::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::Chat::Server>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Chat::Server;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::Chat::Server::_iceI_begin_CreateRoom(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Chat_Server_CreateRoom_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Server_CreateRoom_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Server_CreateRoom_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_Chat_Server_CreateRoom_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Chat::RoomPrx
IceProxy::Chat::Server::end_CreateRoom(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Chat_Server_CreateRoom_name);
    ::Chat::RoomPrx ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::Chat::Server::_iceI_begin_getRooms(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Chat_Server_getRooms_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Server_getRooms_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Server_getRooms_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_Chat_Server_getRooms_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Chat::RoomList
IceProxy::Chat::Server::end_getRooms(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Chat_Server_getRooms_name);
    ::Chat::RoomList ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::Chat::Server::_iceI_begin_FindRoom(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Chat_Server_FindRoom_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Server_FindRoom_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Server_FindRoom_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_Chat_Server_FindRoom_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Chat::RoomPrx
IceProxy::Chat::Server::end_FindRoom(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Chat_Server_FindRoom_name);
    ::Chat::RoomPrx ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::Chat::Server::_iceI_begin_RegisterUser(const ::std::string& iceP_name, const ::std::string& iceP_password, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Chat_Server_RegisterUser_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Server_RegisterUser_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Server_RegisterUser_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        ostr->write(iceP_password);
        result->endWriteParams();
        result->invoke(iceC_Chat_Server_RegisterUser_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::Server::end_RegisterUser(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Chat_Server_RegisterUser_name);
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Chat::UserAlreadyExists&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    result->_readEmptyParams();
}

::Ice::AsyncResultPtr
IceProxy::Chat::Server::_iceI_begin_ChangePassword(const ::Chat::UserPrx& iceP_user, const ::std::string& iceP_oldpassword, const ::std::string& iceP_newpassword, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Server_ChangePassword_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Server_ChangePassword_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_user);
        ostr->write(iceP_oldpassword);
        ostr->write(iceP_newpassword);
        result->endWriteParams();
        result->invoke(iceC_Chat_Server_ChangePassword_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::Server::end_ChangePassword(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Chat_Server_ChangePassword_name);
}

::Ice::AsyncResultPtr
IceProxy::Chat::Server::_iceI_begin_getPassword(const ::std::string& iceP_user, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Server_getPassword_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Server_getPassword_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_user);
        result->endWriteParams();
        result->invoke(iceC_Chat_Server_getPassword_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::Server::end_getPassword(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Chat_Server_getPassword_name);
}

::Ice::AsyncResultPtr
IceProxy::Chat::Server::_iceI_begin_RegisterRoomFactory(const ::Chat::RoomFactoryPrx& iceP_factory, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Server_RegisterRoomFactory_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Server_RegisterRoomFactory_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_factory);
        result->endWriteParams();
        result->invoke(iceC_Chat_Server_RegisterRoomFactory_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::Server::end_RegisterRoomFactory(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Chat_Server_RegisterRoomFactory_name);
}

::Ice::AsyncResultPtr
IceProxy::Chat::Server::_iceI_begin_UnregisterRoomFactory(const ::Chat::RoomFactoryPrx& iceP_factory, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Server_UnregisterRoomFactory_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Server_UnregisterRoomFactory_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_factory);
        result->endWriteParams();
        result->invoke(iceC_Chat_Server_UnregisterRoomFactory_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::Server::end_UnregisterRoomFactory(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Chat_Server_UnregisterRoomFactory_name);
}

::IceProxy::Ice::Object*
IceProxy::Chat::Server::_newInstance() const
{
    return new Server;
}

const ::std::string&
IceProxy::Chat::Server::ice_staticId()
{
    return ::Chat::Server::ice_staticId();
}
::IceProxy::Ice::Object* ::IceProxy::Chat::upCast(::IceProxy::Chat::Room* p) { return p; }

void
::IceProxy::Chat::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::Chat::Room>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Chat::Room;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::Chat::Room::_iceI_begin_getName(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Chat_Room_getName_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Room_getName_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Room_getName_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_Chat_Room_getName_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::std::string
IceProxy::Chat::Room::end_getName(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Chat_Room_getName_name);
    ::std::string ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::Chat::Room::_iceI_begin_getUsers(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Chat_Room_getUsers_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Room_getUsers_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Room_getUsers_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_Chat_Room_getUsers_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Chat::UserList
IceProxy::Chat::Room::end_getUsers(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Chat_Room_getUsers_name);
    ::Chat::UserList ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::Chat::Room::_iceI_begin_AddUser(const ::Chat::UserPrx& iceP_who, const ::std::string& iceP_password, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Room_AddUser_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Room_AddUser_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_who);
        ostr->write(iceP_password);
        result->endWriteParams();
        result->invoke(iceC_Chat_Room_AddUser_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::Room::end_AddUser(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Chat_Room_AddUser_name);
}

::Ice::AsyncResultPtr
IceProxy::Chat::Room::_iceI_begin_SendMessage(const ::Chat::UserPrx& iceP_who, const ::std::string& iceP_message, const ::std::string& iceP_passwd, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Room_SendMessage_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Room_SendMessage_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_who);
        ostr->write(iceP_message);
        ostr->write(iceP_passwd);
        result->endWriteParams();
        result->invoke(iceC_Chat_Room_SendMessage_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::Room::end_SendMessage(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Chat_Room_SendMessage_name);
}

::Ice::AsyncResultPtr
IceProxy::Chat::Room::_iceI_begin_Destroy(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Room_Destroy_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Room_Destroy_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_Chat_Room_Destroy_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::Room::end_Destroy(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Chat_Room_Destroy_name);
}

::Ice::AsyncResultPtr
IceProxy::Chat::Room::_iceI_begin_LeaveRoom(const ::Chat::UserPrx& iceP_who, const ::std::string& iceP_passwd, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_Room_LeaveRoom_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_Room_LeaveRoom_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_who);
        ostr->write(iceP_passwd);
        result->endWriteParams();
        result->invoke(iceC_Chat_Room_LeaveRoom_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

void
IceProxy::Chat::Room::end_LeaveRoom(const ::Ice::AsyncResultPtr& result)
{
    _end(result, iceC_Chat_Room_LeaveRoom_name);
}

::IceProxy::Ice::Object*
IceProxy::Chat::Room::_newInstance() const
{
    return new Room;
}

const ::std::string&
IceProxy::Chat::Room::ice_staticId()
{
    return ::Chat::Room::ice_staticId();
}
::IceProxy::Ice::Object* ::IceProxy::Chat::upCast(::IceProxy::Chat::RoomFactory* p) { return p; }

void
::IceProxy::Chat::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< ::IceProxy::Chat::RoomFactory>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Chat::RoomFactory;
        v->_copyFrom(proxy);
    }
}

::Ice::AsyncResultPtr
IceProxy::Chat::RoomFactory::_iceI_begin_createRoom(const ::std::string& iceP_name, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Chat_RoomFactory_createRoom_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_RoomFactory_createRoom_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_RoomFactory_createRoom_name, ::Ice::Normal, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_name);
        result->endWriteParams();
        result->invoke(iceC_Chat_RoomFactory_createRoom_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Chat::RoomPrx
IceProxy::Chat::RoomFactory::end_createRoom(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Chat_RoomFactory_createRoom_name);
    ::Chat::RoomPrx ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::Ice::AsyncResultPtr
IceProxy::Chat::RoomFactory::_iceI_begin_getRooms(const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_Chat_RoomFactory_getRooms_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_Chat_RoomFactory_getRooms_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_Chat_RoomFactory_getRooms_name, ::Ice::Normal, context);
        result->writeEmptyParams();
        result->invoke(iceC_Chat_RoomFactory_getRooms_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Chat::RoomList
IceProxy::Chat::RoomFactory::end_getRooms(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_Chat_RoomFactory_getRooms_name);
    ::Chat::RoomList ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

::IceProxy::Ice::Object*
IceProxy::Chat::RoomFactory::_newInstance() const
{
    return new RoomFactory;
}

const ::std::string&
IceProxy::Chat::RoomFactory::ice_staticId()
{
    return ::Chat::RoomFactory::ice_staticId();
}

Chat::User::~User()
{
}

::Ice::Object* Chat::upCast(::Chat::User* p) { return p; }


namespace
{
const ::std::string iceC_Chat_User_ids[2] =
{
    "::Chat::User",
    "::Ice::Object"
};

}

bool
Chat::User::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Chat_User_ids, iceC_Chat_User_ids + 2, s);
}

::std::vector< ::std::string>
Chat::User::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Chat_User_ids[0], &iceC_Chat_User_ids[2]);
}

const ::std::string&
Chat::User::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Chat::User::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Chat::User";
    return typeId;
#else
    return iceC_Chat_User_ids[0];
#endif
}

bool
Chat::User::_iceD_SendMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Chat::RoomPrx iceP_where;
    ::Chat::UserPrx iceP_who;
    ::std::string iceP_message;
    istr->read(iceP_where);
    istr->read(iceP_who);
    istr->read(iceP_message);
    inS.endReadParams();
    this->SendMessage(iceP_where, iceP_who, iceP_message, current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::User::_iceD_SendPrivateMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Chat::UserPrx iceP_who;
    ::std::string iceP_message;
    istr->read(iceP_who);
    istr->read(iceP_message);
    inS.endReadParams();
    this->SendPrivateMessage(iceP_who, iceP_message, current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::User::_iceD_getName(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::std::string ret = this->getName(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

namespace
{
const ::std::string iceC_Chat_User_all[] =
{
    "SendMessage",
    "SendPrivateMessage",
    "getName",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

bool
Chat::User::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Chat_User_all, iceC_Chat_User_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Chat_User_all)
    {
        case 0:
        {
            return _iceD_SendMessage(in, current);
        }
        case 1:
        {
            return _iceD_SendPrivateMessage(in, current);
        }
        case 2:
        {
            return _iceD_getName(in, current);
        }
        case 3:
        {
            return _iceD_ice_id(in, current);
        }
        case 4:
        {
            return _iceD_ice_ids(in, current);
        }
        case 5:
        {
            return _iceD_ice_isA(in, current);
        }
        case 6:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
Chat::User::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::Chat::User, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Chat::User::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::Chat::User, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
Chat::_icePatchObjectPtr(UserPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Chat::UserPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Chat::User::ice_staticId(), v);
    }
}

Chat::Server::~Server()
{
}

::Ice::Object* Chat::upCast(::Chat::Server* p) { return p; }


namespace
{
const ::std::string iceC_Chat_Server_ids[2] =
{
    "::Chat::Server",
    "::Ice::Object"
};

}

bool
Chat::Server::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Chat_Server_ids, iceC_Chat_Server_ids + 2, s);
}

::std::vector< ::std::string>
Chat::Server::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Chat_Server_ids[0], &iceC_Chat_Server_ids[2]);
}

const ::std::string&
Chat::Server::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Chat::Server::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Chat::Server";
    return typeId;
#else
    return iceC_Chat_Server_ids[0];
#endif
}

bool
Chat::Server::_iceD_CreateRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    ::Chat::RoomPrx ret = this->CreateRoom(iceP_name, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::Server::_iceD_getRooms(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::Chat::RoomList ret = this->getRooms(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::Server::_iceD_FindRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    ::Chat::RoomPrx ret = this->FindRoom(iceP_name, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::Server::_iceD_RegisterUser(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    ::std::string iceP_password;
    istr->read(iceP_name);
    istr->read(iceP_password);
    inS.endReadParams();
    this->RegisterUser(iceP_name, iceP_password, current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Server::_iceD_ChangePassword(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Chat::UserPrx iceP_user;
    ::std::string iceP_oldpassword;
    ::std::string iceP_newpassword;
    istr->read(iceP_user);
    istr->read(iceP_oldpassword);
    istr->read(iceP_newpassword);
    inS.endReadParams();
    this->ChangePassword(iceP_user, iceP_oldpassword, iceP_newpassword, current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Server::_iceD_getPassword(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_user;
    istr->read(iceP_user);
    inS.endReadParams();
    this->getPassword(iceP_user, current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Server::_iceD_RegisterRoomFactory(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Chat::RoomFactoryPrx iceP_factory;
    istr->read(iceP_factory);
    inS.endReadParams();
    this->RegisterRoomFactory(iceP_factory, current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Server::_iceD_UnregisterRoomFactory(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Chat::RoomFactoryPrx iceP_factory;
    istr->read(iceP_factory);
    inS.endReadParams();
    this->UnregisterRoomFactory(iceP_factory, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_Chat_Server_all[] =
{
    "ChangePassword",
    "CreateRoom",
    "FindRoom",
    "RegisterRoomFactory",
    "RegisterUser",
    "UnregisterRoomFactory",
    "getPassword",
    "getRooms",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

bool
Chat::Server::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Chat_Server_all, iceC_Chat_Server_all + 12, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Chat_Server_all)
    {
        case 0:
        {
            return _iceD_ChangePassword(in, current);
        }
        case 1:
        {
            return _iceD_CreateRoom(in, current);
        }
        case 2:
        {
            return _iceD_FindRoom(in, current);
        }
        case 3:
        {
            return _iceD_RegisterRoomFactory(in, current);
        }
        case 4:
        {
            return _iceD_RegisterUser(in, current);
        }
        case 5:
        {
            return _iceD_UnregisterRoomFactory(in, current);
        }
        case 6:
        {
            return _iceD_getPassword(in, current);
        }
        case 7:
        {
            return _iceD_getRooms(in, current);
        }
        case 8:
        {
            return _iceD_ice_id(in, current);
        }
        case 9:
        {
            return _iceD_ice_ids(in, current);
        }
        case 10:
        {
            return _iceD_ice_isA(in, current);
        }
        case 11:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
Chat::Server::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::Chat::Server, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Chat::Server::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::Chat::Server, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
Chat::_icePatchObjectPtr(ServerPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Chat::ServerPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Chat::Server::ice_staticId(), v);
    }
}

Chat::Room::~Room()
{
}

::Ice::Object* Chat::upCast(::Chat::Room* p) { return p; }


namespace
{
const ::std::string iceC_Chat_Room_ids[2] =
{
    "::Chat::Room",
    "::Ice::Object"
};

}

bool
Chat::Room::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Chat_Room_ids, iceC_Chat_Room_ids + 2, s);
}

::std::vector< ::std::string>
Chat::Room::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Chat_Room_ids[0], &iceC_Chat_Room_ids[2]);
}

const ::std::string&
Chat::Room::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Chat::Room::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Chat::Room";
    return typeId;
#else
    return iceC_Chat_Room_ids[0];
#endif
}

bool
Chat::Room::_iceD_getName(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::std::string ret = this->getName(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::Room::_iceD_getUsers(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::Chat::UserList ret = this->getUsers(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::Room::_iceD_AddUser(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Chat::UserPrx iceP_who;
    ::std::string iceP_password;
    istr->read(iceP_who);
    istr->read(iceP_password);
    inS.endReadParams();
    this->AddUser(iceP_who, iceP_password, current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Room::_iceD_SendMessage(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Chat::UserPrx iceP_who;
    ::std::string iceP_message;
    ::std::string iceP_passwd;
    istr->read(iceP_who);
    istr->read(iceP_message);
    istr->read(iceP_passwd);
    inS.endReadParams();
    this->SendMessage(iceP_who, iceP_message, iceP_passwd, current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Room::_iceD_Destroy(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    this->Destroy(current);
    inS.writeEmptyParams();
    return true;
}

bool
Chat::Room::_iceD_LeaveRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::Chat::UserPrx iceP_who;
    ::std::string iceP_passwd;
    istr->read(iceP_who);
    istr->read(iceP_passwd);
    inS.endReadParams();
    this->LeaveRoom(iceP_who, iceP_passwd, current);
    inS.writeEmptyParams();
    return true;
}

namespace
{
const ::std::string iceC_Chat_Room_all[] =
{
    "AddUser",
    "Destroy",
    "LeaveRoom",
    "SendMessage",
    "getName",
    "getUsers",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

bool
Chat::Room::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Chat_Room_all, iceC_Chat_Room_all + 10, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Chat_Room_all)
    {
        case 0:
        {
            return _iceD_AddUser(in, current);
        }
        case 1:
        {
            return _iceD_Destroy(in, current);
        }
        case 2:
        {
            return _iceD_LeaveRoom(in, current);
        }
        case 3:
        {
            return _iceD_SendMessage(in, current);
        }
        case 4:
        {
            return _iceD_getName(in, current);
        }
        case 5:
        {
            return _iceD_getUsers(in, current);
        }
        case 6:
        {
            return _iceD_ice_id(in, current);
        }
        case 7:
        {
            return _iceD_ice_ids(in, current);
        }
        case 8:
        {
            return _iceD_ice_isA(in, current);
        }
        case 9:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
Chat::Room::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::Chat::Room, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Chat::Room::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::Chat::Room, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
Chat::_icePatchObjectPtr(RoomPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Chat::RoomPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Chat::Room::ice_staticId(), v);
    }
}

Chat::RoomFactory::~RoomFactory()
{
}

::Ice::Object* Chat::upCast(::Chat::RoomFactory* p) { return p; }


namespace
{
const ::std::string iceC_Chat_RoomFactory_ids[2] =
{
    "::Chat::RoomFactory",
    "::Ice::Object"
};

}

bool
Chat::RoomFactory::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_Chat_RoomFactory_ids, iceC_Chat_RoomFactory_ids + 2, s);
}

::std::vector< ::std::string>
Chat::RoomFactory::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_Chat_RoomFactory_ids[0], &iceC_Chat_RoomFactory_ids[2]);
}

const ::std::string&
Chat::RoomFactory::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
Chat::RoomFactory::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::Chat::RoomFactory";
    return typeId;
#else
    return iceC_Chat_RoomFactory_ids[0];
#endif
}

bool
Chat::RoomFactory::_iceD_createRoom(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_name;
    istr->read(iceP_name);
    inS.endReadParams();
    ::Chat::RoomPrx ret = this->createRoom(iceP_name, current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

bool
Chat::RoomFactory::_iceD_getRooms(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Normal, current.mode);
    inS.readEmptyParams();
    ::Chat::RoomList ret = this->getRooms(current);
    ::Ice::OutputStream* ostr = inS.startWriteParams();
    ostr->write(ret);
    inS.endWriteParams();
    return true;
}

namespace
{
const ::std::string iceC_Chat_RoomFactory_all[] =
{
    "createRoom",
    "getRooms",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

bool
Chat::RoomFactory::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_Chat_RoomFactory_all, iceC_Chat_RoomFactory_all + 6, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_Chat_RoomFactory_all)
    {
        case 0:
        {
            return _iceD_createRoom(in, current);
        }
        case 1:
        {
            return _iceD_getRooms(in, current);
        }
        case 2:
        {
            return _iceD_ice_id(in, current);
        }
        case 3:
        {
            return _iceD_ice_ids(in, current);
        }
        case 4:
        {
            return _iceD_ice_isA(in, current);
        }
        case 5:
        {
            return _iceD_ice_ping(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}

void
Chat::RoomFactory::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    Ice::StreamWriter< ::Chat::RoomFactory, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
Chat::RoomFactory::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    Ice::StreamReader< ::Chat::RoomFactory, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}

void
Chat::_icePatchObjectPtr(RoomFactoryPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::Chat::RoomFactoryPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::Chat::RoomFactory::ice_staticId(), v);
    }
}

namespace Ice
{
}

#endif
